Update auto.yml

diff --git a/.github/workflows/auto.yml b/.github/workflows/auto.yml
--- a/.github/workflows/auto.yml
+++ b/.github/workflows/auto.yml
@@ -28,9 +28,13 @@ jobs:
       - uses: actions/setup-node@v2
       - name: Run Project
         run: |
-          cd workflows
-          yarn
-          yarn checkin
+          for attempt in {1..3}; do
+            cd workflows && yarn && yarn checkin && exit 0
+            echo "$attempt, retrying..."
+            sleep 1000*60*30
+          done
+          echo "All attempts failed."
+          exit 1
 
 #  SeaGold:
 #    needs: CheckIn
